### ISSUE TITLE
HTTP::Request is not composable

### ISSUE THREAD

**Issue by JJ** [tony-o/perl6-http-server-threaded#5]
Test fails with:
```
===SORRY!=== Error while compiling /home/jmerelo/Code/forks/perl6/perl6-http-server-threaded/lib/HTTP/Server/Threaded/Request.pm6 (HTTP::Server::Threaded::Request)
HTTP::Request is not composable, so HTTP::Server::Threaded::Request cannot compose it
at /home/jmerelo/Code/forks/perl6/perl6-http-server-threaded/lib/HTTP/Server/Threaded/Request.pm6 (HTTP::Server::Threaded::Request):2
```
Refs: perl6/ecosystem-unbitrot#419

**Comment by jonathanstowe** [comment]
This exactly the problem that auth qualifying the same named class in H::UA was intended to fix.

**Comment by jonathanstowe** [comment]
Specifically auth qualifying the HTTP::Request and Response in this module should fix. But renaming would be better.

**Comment by JJ** [comment]
The problem is downstream, I would say, namely in HTTP::Server. Which was unreleased, BTW, or never released. I've discovered a [small rat's nest there](https://github.com/perl6/perl6-http-server/issues)

**Comment by tony-o** [comment]
This module should be deprecated and not used on versions of 6.c+ ish

**Comment by JJ** [comment]
Should we then retire it from the ecosystem?
